# Generated by Django 5.0.4 on 2024-05-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_timestamp_tweetliked_tweet_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='liked',
            new_name='likes',
        ),
    ]
